engines:
  csslint:
    enabled: false
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - python
  eslint:
    enabled: true
    config:
      config: .eslintrc
    extensions:
      - .js
  fixme:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
    - "**.coffee"
    - "**.js"
    - "**.py"
exclude_paths:
  - tests/
  - django_otp/*/migrations/
