language: python
python:
  - 3.5
sudo: false
cache:
  apt: true
  pip: true
  directories:
    - "${HOME}/.npm"
    - "${HOME}/.nvm"
    - "node_modules"
    - "../venv"
compiler: g++-4.8
env:
  global:
    - CXX=g++-4.8
    - node_mode=production
node_js:
  - "node"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - deadsnakes
    packages:
      - g++-4.8
      - pandoc
      - libnotify-bin
install:
  - "npm install"
  - "npm update"
  - "pyvenv-3.5 ../venv"
  - "source ../venv/bin/activate"
  - "pip install -r requirements.txt"
  - "deactivate"
script:
  - "source ../venv/bin/activate"
  - "npm test"
  - "deactivate"
after_success:
  - "source ../venv/bin/activate"
  - "coveralls"
  - "codeclimate-test-reporter"
  - "deactivate"
before_deploy:
  - "pandoc -f markdown -t rst -o README.rst README.md"
deploy:
  provider: pypi
  skip_cleanup: true
  distributions: sdist
  on:
    tags: true
  user:
    secure: >-
      OSquy22jQQ3nJiO4N8elR6eVwgX4b7rzLJIzr+15A8jQVCsNlamm0VLF4ymVT5/3Wy8Cm3VX
      lsYgQn0Sc96Yk3i+PFRkxb9H3s7gtGYitqaOW9k4+QcztbJKhYxKGO5NPRIeUAGPMCQG9BUa
      y1lZic4wbg+g0Iry7lUSf+07WRbawwuulAByuzqFp8gB9cJNg5cfQuAF4Y2XmckmwnjP6NNs
      uz5pb0rwySfRFcYQTpl4Pp4IW7NWKJEhid8pTz4GnHU2sctJhZwIPjP0ldYRvSedtwNy+yql
      5qDgZdZr4aPzHwhy5OobIq8fMxJpHT7q7M9IzOPfcfqknfsTjHCEuuQEYeogCOwVDlcl6qea
      runMGH+D+e4BaNxgJG/8r1qFR0AvZbrWGKm6GwK/cgkDKyq2LdMMzdyB319tPp3wDoGkV+E9
      ZZY/xsu2nPG3QbrUHZV6kVFrJ+ZLLXcW5TPhWD/D/4/TP21eSwBJ31q0hNPLs5F/WJyUjgsv
      q7ZxAqIaHRiW25gHjWnvoz7VJgOAWucCLX66t2wMISfOheHUbmjC9YEbD7HvtbR/ovPv31ER
      BFTAHn1knIjWFgxSAAsatQV95xj7MRfZGAQl8hOmdgJoIkeYzc2+o5bsyCTmGSnYcdHhkRQO
      T5aJ+Fgn7hwydCGddHhpclFhJ080yOOc5Is=
  password:
    secure: >-
      t3bGQ0oOPj6zjMMUibn16Nf44ZbYOGObVISY/UCzvYYbb0LeMHTwyu4ohx9mwC4oJX+t4Qoz
      nAiQkWq+yK2qvq6LnvsvkOvHaHBENxgh0sU/djObo2KEXi5QlnUmDzNsVUTIbSILkEwY/56f
      bSOgWTk6w5qkdylAEuUls497md8lVp4QUgDnxm09GPkUXaSg0WmIPDVImp4eEKBbB729Q/kL
      PhOJYKPvQ6xqbE5jVL0az1BeYbh+SNRZTsR4lTFoZkReqzGhtWL6EE1YWhb3h6b021kPVN3q
      9WWJ2PCoVyU2JzCvkXSTNaUSHqTzzfpqMuOihMK/m8XMaPFTEd9P+O5REstR9wgC+O3dPeon
      OHfqQQd4LoWHRkZuRdj3EZuHpqGEPZyGgIqRO6WisJ8k5JzkzFy5L2oj4vrABu0cZD402tGA
      nn9eaxrYoDZPZccDVuMYhPWAZfPK5KmkmQVAvn9pf3Krz0GZQaVjuanaeO2zdFRBp81N30rZ
      EdisRNQ+EjprCUpd7Zf3Gk8AZf5Rn6xxqpEA7h7wEnPARHbhEn2U7MzGAx25fFYO0FEBPWOU
      jXhKhwYk27bp/a7mlNXSPOXpsES4FGTkoXneulm8JfgY9GAQhM/z9BRURUvT+WBz4HbOApur
      HpA0UIMCFrVSnKOJfEY+/QAar79FvrrLa0c=
